package com.ferwafa.common;

public enum NotificationType {
    REFEREE_ASSIGNED,
    REPORT_SUBMITTED,
    REPORT_APPROVED,
    TRANSFER_REQUESTED,
    TRANSFER_APPROVED,
    TRANSFER_REJECTED,
    TRANSFER_COMPLETED,
    PLAYER_SUSPENDED,
    CLUB_SANCTION,
    FIXTURE_POSTPONED
}
